name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if you're using that branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # current directory (includes index.html)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
